[package]
name = "mlib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv-async = { version = "1.1.6", features = ["tokio"], optional = true }
dirs = { version = "4.0.0", optional = true }
futures-util = { version = "0.3.18", optional = true }
glob = { version = "0.3.0", optional = true }
memchr = { version = "2.4.1", optional = true }
once_cell = { version = "1.8.0", optional = true }
parking_lot = { version = "0.11.2", optional = true }
regex = { version = "1.5.4", optional = true }
serde = { version = "1.0.131", features = ["derive"], optional = true }
serde_json = { version = "1.0.73", optional = true }
thiserror = { version = "1.0.30" }
tokio = { version = "1.14.0", features = ["net", "fs", "process", "rt", "io-util"], optional = true }
tokio-stream = { version = "0.1.8", features = ["fs", "io-util"], optional = true }
tracing = { version = "0.1.29", optional = true }
whoami = { version = "1.2.1", optional = true }
async_once = { version = "0.2.1", optional = true }
arc-swap = { version = "1.5.0", optional = true }
pin-project = { version = "1.0.9", optional = true }

[features]
default = [
    "socket",
    "playlist",
    "ytdl",
    "downloads",
    "items",
    "queue",
]
socket = [
    "items",

    "futures-util",
    "whoami",
    "tracing",
    "tokio",
    "regex",
    "parking_lot",
    "once_cell",
    "glob",
    "serde_json",
    "async_once",
    "arc-swap",
    "pin-project",
    "serde",
]
playlist = [
    "items",

    "once_cell",
    "csv-async",
    "serde",
    "dirs",
    "tokio",
    "futures-util",
    "memchr",
    "regex",
]
ytdl = [
    "items",

    "once_cell",
    "tokio",
    "tokio-stream",
    "pin-project",
    "futures-util",
    "regex",
]
downloads = [
    "items",
    "queue",

    "tokio",
    "tokio-stream",
    "futures-util",
    "glob"
]
items = [
    "playlist",

    "serde",
    "once_cell",
]
queue = [
    "socket",
]
