[package]
name = "mlib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = { version = "1.1.6", optional = true }
dirs = "4.0.0"
glob = { version = "0.3.0", optional = true }
once_cell = { version = "1.8.0", optional = true }
parking_lot = { version = "0.11.2", optional = true }
regex = { version = "1.5.4", optional = true }
serde = { version = "1.0.131", features = ["derive"], optional = true }
tokio = { version = "1.14.0", features = ["net"], optional = true }
tracing = { version = "0.1.29", optional = true }
whoami = { version = "1.2.1", optional = true }

[features]
default = ["socket", "playlist"]
socket = ["whoami", "tracing", "tokio", "regex", "parking_lot", "once_cell", "glob"]
playlist = ["csv", "serde"]
