[package]
name = "m"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.26"
mlib = { path = "./mlib", default-features = true }
margs = { path = "./margs" }
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread", "rt", "parking_lot"] }
anyhow = "1.0.58"
regex = "1.5.6"
tracing-subscriber = { version = "0.3.11", features = ["registry", "env-filter", "fmt"] }
tracing-log = "0.1.3"
tracing = "0.1.35"
async_once = "0.2.6"
futures-util = "0.3.21"
tokio-stream = { version = "0.1.9", features = ["io-util"] }
itertools = "0.10.3"
memchr = "2.5.0"
tempfile = "3.3.0"
reqwest = { version = "0.11.11", features = ["rustls-tls", "stream"] }
rand = { version = "0.8.5", features = ["getrandom"] }
clipboard = "0.5.0"
once_cell = "1.12.0"
dirs = "4.0.0"
crossterm = "0.23.2"
async-recursion = "1.0.0"
whoami = "1.2.1"
namespaced-tmp = { git = "https://github.com/mendess/namespaced-tmp", features = ["user"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
config = "0.13.1"

[workspace]
members = ["mlib", "margs"]

[features]
