[package]
name = "m"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.25"
mlib = { path = "./mlib", default-features = true }
tokio = { version = "1.14.0", features = ["macros", "rt-multi-thread", "rt"] }
anyhow = "1.0.51"
regex = "1.5.4"
atty = "0.2.14"
term = "0.7.0"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter", "fmt"] }
tracing-log = "0.1.2"
tracing = "0.1.29"
async_once = "0.2.1"
futures-util = "0.3.18"
tokio-stream = { version = "0.1.8", features = ["io-util"] }
itertools = "0.10.3"
memchr = "2.4.1"
tempfile = "3.2.0"
reqwest = { version = "0.11.8", features = ["rustls-tls", "stream"] }
rand = { version = "0.8.4", features = ["getrandom"] }
clipboard = "0.5.0"
once_cell = "1.9.0"
dirs = "4.0.0"

[workspace]
members = ["mlib"]

[features]
