[package]
name = "m"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.25"
mlib = { path = "./mlib", default-features = true }
tokio = { version = "1.14.0", features = ["macros", "rt-multi-thread", "rt"] }
anyhow = "1.0.51"
regex = "1.5.4"

[workspace]
members = ["mlib"]
