[package]
name = "m"
version = "0.3.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.60"
async-recursion = "1.0.0"
structopt = "0.3.26"
tempfile = "3.3.0"
clipboard = "0.5.0"
config = "0.13.2"
crossterm = "0.24.0"
itertools = "0.10.3"
mlib = { path = "./mlib", default-features = true }
rand = { version = "0.8.5", features = ["getrandom"] }
reqwest = { version = "0.11.11", features = ["rustls-tls", "stream"] }
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.15", features = ["registry", "env-filter", "fmt"] }

async_once.workspace = true
cli-daemon.workspace = true
dirs.workspace = true
futures-util.workspace = true
memchr.workspace = true
namespaced-tmp.workspace  = true
once_cell.workspace = true
regex.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio.workspace = true
tokio-stream = { workspace = true, features = ["io-util"] }
tracing.workspace = true
whoami.workspace = true

[workspace]
members = ["mlib", "cli-daemon"]

[workspace.dependencies]
async_once = "0.2.6"
cli-daemon = { path = "./cli-daemon" }
dirs = "4.0.0"
futures-util = "0.3.21"
memchr = "2.5.0"
once_cell = "1.13.0"
regex = "1.6.0"
serde = { version = "1.0.142", features = ["derive"] }
serde_json = "1.0.83"
tokio-stream = { version = "0.1.9", features = ["io-util"] }
tracing = "0.1.36"
whoami = "1.2.1"

[workspace.dependencies.tokio]
version = "1.20.1"
default-features = false
features = ["macros", "rt-multi-thread", "rt", "parking_lot"]

[workspace.dependencies.namespaced-tmp]
git = "https://github.com/mendess/namespaced-tmp"
features = ["user"]
