[package]
name = "mlib"
version = "0.20.8"
edition = { workspace = true }

[dependencies]
arc-swap = { workspace = true, optional = true }
async_once = { workspace = true , optional = true }
base64 = { workspace = true , optional = true }
chrono = { workspace = true, optional = true }
cli-daemon = { path = "../cli-daemon", optional = true }
csv-async = { workspace = true, features = ["tokio"], optional = true }
derive_more = { workspace = true, features = ["from"] }
dirs = { workspace = true, optional = true }
form_urlencoded = { workspace = true }
futures-util = { workspace = true, optional = true }
glob = { workspace = true, optional = true }
libmpv = { git = "https://github.com/sirno/libmpv-rs", optional = true, branch = "upgrade-libmpv" }
memchr = { workspace = true, optional = true }
mpris-server = { workspace = true, optional = true }
namespaced-tmp = { workspace = true, optional = true }
parking_lot = { workspace = true, optional = true }
pin-project = { workspace = true, optional = true }
raii_flock = { workspace = true, optional = true }
regex.workspace = true
reqwest = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"], optional = true }
serde-map-to-array = { workspace = true, features = ["std"], optional = true }
serde_json = { workspace = true, optional = true }
static_assertions = { workspace = true }
tempfile = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
tokio-stream = { workspace = true, features = ["fs", "io-util"], optional = true }
tokio-util = { workspace = true, features = ["compat"], optional = true }
tracing = { workspace = true, optional = true }
trait-gen = { workspace = true, optional = true }
url = { workspace = true, features = ["serde"] }
whoami = { workspace = true, optional = true }
zbus = { workspace = true, optional = true, features = ["tokio"] }

[dependencies.tokio]
workspace = true
features = ["process"]
optional = true

[dev-dependencies]
tracing-subscriber = { workspace = true, features = ["registry", "env-filter", "fmt"] }

[dev-dependencies.tokio]
workspace = true
features = ["net", "fs", "process", "rt", "io-util", "macros", "rt-multi-thread"]

[[example]]
name = "observe"
required-features = ["player"]

[[example]]
name = "ytdl"
required-features = ["ytdl"]

[features]
ytdl = [
    "dep:base64",
    "dep:futures-util",
    "dep:namespaced-tmp",
    "dep:parking_lot",
    "dep:pin-project",
    "dep:thiserror",
    "dep:tokio",
    "dep:tokio-stream",
    "dep:tracing",
    "dep:trait-gen",
]
player = [
    "serde",
    "player-connection",
    "downloads",
    "statistics",

    "dep:libmpv",
    "dep:parking_lot",
    "tokio/io-util",
]
player-connection = [
    "serde",

    "dep:arc-swap",
    "dep:cli-daemon",
    "dep:futures-util",
    "dep:namespaced-tmp",
    "dep:thiserror",
    "dep:tokio",
    "dep:tracing",
]
statistics = [
    "serde",

    "dep:chrono",
    "dep:dirs",
    "dep:raii_flock",
    "dep:serde-map-to-array",
    "dep:serde_json",
    "dep:tempfile",
    "dep:tracing",
    "tokio/fs",
]
playlist = [
    "serde",

    "dep:csv-async",
    "dep:dirs",
    "dep:futures-util",
    "dep:memchr",
    "dep:serde_json",
    "dep:thiserror",
    "dep:tokio",
    "dep:tracing",
]
queue = [
    "playlist",
    "player-connection",
]
downloads = [
    "queue",
    "ytdl",

    "dep:glob",
    "dep:reqwest",
    "reqwest/stream",
    "reqwest/json",
    "dep:tokio-util",
]
serde = ["dep:serde"]
mpris = [
    "dep:mpris-server",
    "dep:zbus",
]
default = [
    "downloads",
    "player",
    "playlist",
    "queue",
    "statistics",
    "ytdl",
    "mpris",
]
